# Generated by Django 4.2.6 on 2023-11-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Prefer not to say', 'Prefer not to say'), ('Male', 'Male')], max_length=100),
        ),
    ]
